version: '3'
services:
  frontend:
    build:
      context: .
    container_name: microservice_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge